# =========================
# CURSOR
# =========================

# Use classic XCursor themes instead of Hyprcursor
cursor {
    enable_hyprcursor = false
}

env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24

# =========================
# MOTION
# =========================

animations {
    enabled = yes

    # smooth mac-like easing
    bezier = mac, 0.05, 0.9, 0.1, 1.05
    bezier = depth, 0.15, 0.85, 0.25, 1.0

    # window motion
    animation = windows, 1, 6, mac, slide
    animation = windowsOut, 1, 6, mac, slide

    # fade in/out
    animation = fade, 1, 7, mac

    # workspace transition (parallax feel)
    animation = workspaces, 1, 6, depth, slide, fade 70%
}

# =========================
# VISUAL
# =========================

general {
    gaps_in = 6
    gaps_out = 14
    border_size = 2
}

decoration {
    rounding = 10

    blur {
        enabled = true
        size = 8 
        passes = 3 
        new_optimizations = true
    }

    active_opacity = 0.80
    inactive_opacity = 0.70
    fullscreen_opacity = 1.0

    shadow {
        enabled = true
        range = 6
        render_power = 3
    }
}
