bind = $mod, RETURN, exec, $terminal						
bind = $mod SHIFT, RETURN, exec, $terminal --class floating-terminal

bind = $mod, bracketright, exec, firefox -P Research --no-remote
bind = $mod, D, exec, pkill wofi || wofi --show drun
bind = $mod SHIFT, G, exec, hyprlock

# screenshots
bind = , Print, exec, hyprshot -m region --clipboard-only
bind = SHIFT, Print, exec, hyprshot -m region --output-folder ~/Pictures/Screenshots
