# disable firefox transparency
windowrule {
	name = firefox-opaque
	match:class = ^(firefox)$
	opacity = 1.0 override 1.0 override
}

# disable virtual machines transparency
windowrule {
	name = qemu-opaque
    match:title = ^.*QEMU.*$
    opacity = 1.0 override 1.0 override
}

# disable telegram transparency
windowrule {
	name = telegram-opaque
	match:class = .*org.telegram.desktop.*
	opacity = 0.95 override 0.95 override
}

# enable wofi blur
layerrule {
    name = wofi-blur
    match:namespace = wofi
    blur = on
    ignore_alpha = 0
}

# enable waybar blur
layerrule {
	name = waybar-blur
	match:namespace = waybar
	blur = on
	ignore_alpha = 0 
}

# make Throne floating (VPN UI)
windowrule {
	name = throne-floating
    match:class = ^(Throne)$
    float = on
    center = on
    size = 1000 600 
    rounding = 10
    fullscreen = 0
    maximize = 0
}

# floating terminal
windowrule {
    name = floating-terminal
    match:class = ^(floating-terminal)$
    float = on
    center = on
    size = 1000 500
}
