# disable firefox transparency
windowrule {
	name = firefox-opaque
	match:class = ^(firefox)$
	opacity = 1.0 override 1.0 override
}

# disable virtual machines transparency
windowrule {
	name = virt-opaque
	match:class = ^(virt-manager)$
	opacity = 1.0 override 1.0 override

}

layerrule {
    name = wofi-blur
    match:namespace = wofi
    blur = on
    ignore_alpha = 0
}

layerrule {
	name = waybar-blur
	match:namespace = waybar
	blur = on
	ignore_alpha = 0
}
