# Enter resize mode
bind = $mod, R, submap, resize
submap = resize

# Resize active window
binde = , J, resizeactive, -20 0
binde = , semicolon, resizeactive, 20 0
binde = , K, resizeactive, 0 20
binde = , L, resizeactive, 0 -20

# Exit resize mode
bind = $mod, R, submap, reset
bind = , Escape, submap, reset
bind = , Return, submap, reset

submap = reset
