$mod = ALT 

$terminal = alacritty

$scriptsDir = ~/.config/hypr/scripts/

# $wallpaper = ~/Pictures/Wallpapers/gora_sneg_derevia_938847_1920x1080.jpg
# $wallpaper = ~/Pictures/Wallpapers/1561574084_www.GetBg.net_Anime_The_girl_looks_at_the_city_at_night__anime_girl_fairy_Madoka_108890_.jpg
$wallpaper = ~/Pictures/Wallpapers/forest_mountains.jpg
