source = ~/.config/hypr/modules/config.lua

general {
    disable_loading_message = true
    hide_cursor = true
}

background {
    path = ~/Pictures/Wallpapers/forest_mountains.jpg
    blur_passes = 3
    blur_size = 8
}

label {
    text = cmd[update:1000] echo "$(date +'%H:%M')"

    font_size = 68
    color = rgb(ffffff)

    position = 0, 90
    halign = center
    valign = center
}

input-field {
    size = 320, 56

    position = 0, -40
    halign = center
    valign = center

    rounding = 999

    outline_thickness = 2

    outer_color = rgb(666666)
    inner_color = rgba(00000033)
    font_color = rgb(ffffff)

    dots_size = 0.30
    dots_spacing = 0.30

    placeholder_text =
    fade_on_empty = false
}
